### ISSUE TITLE
[RelatedItems] Axios Get Request

### ISSUE THREAD

**Issue by justjjasper** [RFP2209-CORN/FEC-Project-Atelier#100]
https://github.com/RFP2209-CORN/FEC-Project-Atelier/blob/8d18ce8bc4e75da1cfb2f4147d9bd5259bf91441/client/src/components/RelatedItems/ComparisonModal.jsx#L7-L27

You can save the expense of using a get request by ditching the last axios get request (Line 22).
ProductsInfo is called at the top level of the app, and you can pass down the productInfo as a prop into the ComparisonModal component.

**Comment by joshgarza** [comment]
Thanks Jasper! Implemented the change
