### ISSUE TITLE
[RelatedItems] Left and Right Arrow Feature

### ISSUE THREAD

**Issue by justjjasper** [RFP2209-CORN/FEC-Project-Atelier#101]
https://github.com/RFP2209-CORN/FEC-Project-Atelier/blob/8d18ce8bc4e75da1cfb2f4147d9bd5259bf91441/client/src/components/RelatedItems/RelatedItems.jsx#L36-L61

Just a suggestion if you would like to implement a functionality where the left/right arrows don't render if you're at the start/end of the carousel respectively.

You would need to add an additional condition within Line 39, where the ```startIndex``` is not equal to 0.
And another condition within Line 57, where the ```startIndex +  4``` is less than/equal to the length of the ```relatedItems``` by 1.

A little disclaimer though, this would mess with the CSS since the arrows would not render and throw the related items carousel off centered. Which would lead to another CSS debugging process.

**Comment by joshgarza** [comment]
Thanks! Implemented the changes here and since the arrow functionality should be the same for OutfitCreation, I refactored the arrow display there as well. I was able to use the same conditional rendering for a transparent arrow so I didn't have to do any additional CSS debugging.
