### ISSUE TITLE
[QnA] Implementing a search for Answers

### ISSUE THREAD

**Issue by justjjasper** [RFP2209-CORN/FEC-Project-Atelier#98]
https://github.com/RFP2209-CORN/FEC-Project-Atelier/blob/8d18ce8bc4e75da1cfb2f4147d9bd5259bf91441/client/src/components/Q%26A/QA.jsx#L21-L36

Could add a logic to add answers within the for loop.

// iterate through questions list
  // create a variable thats the currentQuestion 
  // make a for in loop through the current Question
    // if the currentQuestion's Key's body includes the query/entry/value (in your code its the value)
    // push that currentQuestion's Key's body into the container

You can add this code under Line 25 and Line 30.

**Comment by hieungo89** [comment]
Thanks @justjjasper! I implemented your suggestion!
