### ISSUE TITLE
[QnA] Optional Chaining

### ISSUE THREAD

**Issue by justjjasper** [RFP2209-CORN/FEC-Project-Atelier#99]
https://github.com/RFP2209-CORN/FEC-Project-Atelier/blob/8d18ce8bc4e75da1cfb2f4147d9bd5259bf91441/client/src/components/Q%26A/IndividualAnswer.jsx#L13-L23

The **if** statement on Line 14 can be removed and you can handle that error that it was taking care of (where ```photos``` is undefined) by implementing optional chaining. You would add a ? in front of ```photos``` and before the . 
For more info on optional chaining: https://javascript.info/optional-chaining

**Comment by hieungo89** [comment]
👍 got it!
